title:  <p align="center"> Paratyaksh Singh </p>
logo: /assets/img/Profile Pic.jpeg

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/paratyaksh-singh/">LinkedIn</a> |
  <a href="https://github.com/Paratyaksh03/">GitHub</a>
  <br>   
  I'm learning Data Science, Machine learning & AI Strategy.
  Would like to work in AI-ML based prod development in E-Com companies.
  <br>
  </p>

github:
  is_project_page: false
theme: jekyll-theme-minimal
